### ISSUE TITLE
17. Project Structure /assets/index.js page

### ISSUE THREAD

**Issue by nicangeli** [jeffhandley/QuickReactions#1]
In order to reference the new structure, I've had to change /src/server.jsx to include the <script> tag 

```
<script src="/Pages/index.js"></script>
```

rather than 

```
<script src="/assets/index.js"></script>
```

And then had to create a static route to /Pages

```
app.use('/Pages',
    express.static(path.join(__dirname, 'Pages')))
```

Is this wrong? Couldn't get the tut working past this point without doing this

**Comment by jeffhandley** [comment]
Thanks a ton for reporting this and figuring out what I'd missed in the tutorial!

**Comment by nicangeli** [comment]
Great resource. Thanks
