### ISSUE TITLE
Warning: React attempted to reuse markup in a container but the checksum was invalid.

### ISSUE THREAD

**Issue by mattdufeu** [jeffhandley/QuickReactions#2]
After completing the tutorial, the site behaves as described but the browsers console contains:

``` javascript
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) reactid=".egwbkqfnr4"><div data-reactid=
 (server) reactid=".egwbkqfnr4.1.1.0"><div data-re
```

Is that something to worry about or expected because it's isomorphic?

**Comment by jeffhandley** [comment]
@maconley just observed the exact same thing.  It looks like this is because the message is expected to render differently between the server and client, so it's "by design."  However, to make the tutorial more clear, @maconley is going to try to fix this by making the client initially render the same message as the server and then change it on a setTimeout.

**Comment by mattdufeu** [comment]
Ah ok, that makes sense.

**Comment by jeffhandley** [comment]
Updated the tutorial to add a [step 20](http://jeffhandley.github.io/QuickReactions/20-final-cleanup) that addresses this issue.  Thanks for reporting it!

**Comment by jiv-e** [comment]
Did you know that you can use componentDidMount method instead of setInterval?

Inside Components/HelloWorld.jsx:

```
var React = require('react')

module.exports = React.createClass({
  getInitialState: function() {
    return {
      message: <div>This is from the HelloWorld.jsx component on the server.</div>
    };
  },
  componentDidMount: function() {
    this.setState({
      message: <div>This is from the HelloWorld.jsx component on the client.</div>
    });
  }
  render: function() {
    return (
      {this.state.message}
    )
  }
})
```

**Comment by jeffhandley** [comment]
Yeah, I considered switching over to that but I wanted to leave it as is so that it remains apparent that this is happening on the client (with a little delay/flicker) and with it being in code that is clearly only running on the client.

Thanks though!
