### ISSUE TITLE
http://jeffhandley.github.io/QuickReactions/11-routing

### ISSUE THREAD

**Issue by noinarisak** [jeffhandley/QuickReactions#7]
Thank you @jeffhandley for putting this tutorial together!

I wanted to mention that I ran into an issue with step 11 and found the below code did not work for me.

```
app.use('/Components',
  express.static(path.join(path.join(__dirname, '..'), 
  'Components')))
```

I discovered that the static path need to go to `lib/` folder. The following resolved my issue.

```
app.use('/Components',
  express.static(path.join(path.join(__dirname, '..'), 
  'lib/Components')))
```

I wanted to share this with your readers. Thank you again for the tutorial!

**Comment by noinarisak** [comment]
Duh! Reading Step 12 you mention the error. Please ignore.

**Comment by jeffhandley** [comment]
Thanks!  Would you be interested in submitting a pull request with that fix?

**Comment by jeffhandley** [comment]
I'm open to suggestions for how to avoid the confusion though.  Please let me know what you think.

**Comment by noinarisak** [comment]
Hey @jeffhandley,
Duh again! It actually is a issue. What you mention in Step 12 was a different case. 

I notice that the same code block is reference through out Step 12 to 14. Let me confirm by going through the tutorial and I'll submit a pull request. 

Great work Jeff!

**Comment by noinarisak** [comment]
After getting a refresher look at Step 11, I found there is no issue with your example code. The issue that I was facing was all file permission in the /Component folder. A little chmod got everything working as expected.

**Comment by jeffhandley** [comment]
Thanks for following up!
